# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.client_id import ClientID  # noqa: F401,E501
from swagger_server import util


class CreditScore(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, client_id: ClientID=None, credit_score: float=None):  # noqa: E501
        """CreditScore - a model defined in Swagger

        :param client_id: The client_id of this CreditScore.  # noqa: E501
        :type client_id: ClientID
        :param credit_score: The credit_score of this CreditScore.  # noqa: E501
        :type credit_score: float
        """
        self.swagger_types = {
            'client_id': ClientID,
            'credit_score': float
        }

        self.attribute_map = {
            'client_id': 'clientId',
            'credit_score': 'credit_score'
        }
        self._client_id = client_id
        self._credit_score = credit_score

    @classmethod
    def from_dict(cls, dikt) -> 'CreditScore':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreditScore of this CreditScore.  # noqa: E501
        :rtype: CreditScore
        """
        return util.deserialize_model(dikt, cls)

    @property
    def client_id(self) -> ClientID:
        """Gets the client_id of this CreditScore.


        :return: The client_id of this CreditScore.
        :rtype: ClientID
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id: ClientID):
        """Sets the client_id of this CreditScore.


        :param client_id: The client_id of this CreditScore.
        :type client_id: ClientID
        """

        self._client_id = client_id

    @property
    def credit_score(self) -> float:
        """Gets the credit_score of this CreditScore.


        :return: The credit_score of this CreditScore.
        :rtype: float
        """
        return self._credit_score

    @credit_score.setter
    def credit_score(self, credit_score: float):
        """Sets the credit_score of this CreditScore.


        :param credit_score: The credit_score of this CreditScore.
        :type credit_score: float
        """

        self._credit_score = credit_score
